# ruff: noqa: E501  (long lines of SVG markup)
"""Draw the open -> 50% -> open animations, in the icon's style.

Writes two SVGs next to this script, with the same timing so they play in
step side by side:

- shades-cover-group.svg: a plain Home Assistant cover group, which sends
  every shade 50% of its own travel.
- shades-aligned.svg: an Aligned Shade Group, which staggers starts so the
  hemlines meet and stay level.

Run with `python assets/make_animations.py`. Heights are in the icon's
coordinates (y grows downward), and hemlines move in a straight line with
position (no roller curve).
"""

from pathlib import Path

WINDOWS = [(10, 22, 204), (94, 58, 140), (178, 40, 206)]  # x, top, height
SPEED = 40.0  # hemline speed shared by every shade, units/s
PAUSE = 1.0  # wait before each command, s
LINEAR = "0 0 1 1"


def open_hemline(top: float) -> float:
    return top + 6


def closed_hemline(top: float, height: float) -> float:
    return top + height - 4


def travel_s(from_h: float, to_h: float) -> float:
    return abs(to_h - from_h) / SPEED


OPENS = [open_hemline(top) for _, top, _ in WINDOWS]
CLOSEDS = [closed_hemline(top, height) for _, top, height in WINDOWS]

# Cover group: every shade to the middle of its own range, all at once.
GROUP_TARGETS = [(o + c) / 2 for o, c in zip(OPENS, CLOSEDS)]
GROUP_DELAYS = [0.0] * len(WINDOWS)

# Aligned: one height halfway through the group's range; moving down, the
# highest hemline starts first and each other shade when it reaches it.
LEVEL = (min(OPENS) + max(CLOSEDS)) / 2
ALIGNED_TARGETS = [LEVEL] * len(WINDOWS)
ALIGNED_DELAYS = [travel_s(min(OPENS), o) for o in OPENS]

# Shared timeline, so both commands happen at the same moment in both files.
DOWN_AT = PAUSE
DOWN_END = DOWN_AT + max(
    d + travel_s(o, t)
    for targets, delays in [
        (GROUP_TARGETS, GROUP_DELAYS),
        (ALIGNED_TARGETS, ALIGNED_DELAYS),
    ]
    for o, t, d in zip(OPENS, targets, delays)
)
UP_AT = DOWN_END + PAUSE
UP_END = UP_AT + max(
    travel_s(t, o)
    for targets in [GROUP_TARGETS, ALIGNED_TARGETS]
    for o, t in zip(OPENS, targets)
)
LOOP_S = UP_END + PAUSE


def keyframes(
    open_h: float, target_h: float, down_delay: float
) -> list[tuple[float, float]]:
    """(time, hemline) for one shade: down to its target, then back up.

    Going up from level, every shade starts at once and each stops at its own
    top, so neither version staggers the up move.
    """
    down_start = DOWN_AT + down_delay
    return [
        (0, open_h),
        (down_start, open_h),
        (down_start + travel_s(open_h, target_h), target_h),
        (UP_AT, target_h),
        (UP_AT + travel_s(target_h, open_h), open_h),
        (LOOP_S, open_h),
    ]


def animate(attr: str, frames: list[tuple[float, float]], value) -> str:
    times = ";".join(f"{t / LOOP_S:.4f}" for t, _ in frames)
    values = ";".join(f"{value(h):.2f}" for _, h in frames)
    splines = ";".join([LINEAR] * (len(frames) - 1))
    return (
        f'<animate attributeName="{attr}" dur="{LOOP_S:.3f}s" repeatCount="indefinite" '
        f'calcMode="spline" keyTimes="{times}" values="{values}" keySplines="{splines}"/>'
    )


def svg(title: str, targets: list[float], delays: list[float], hemline: bool) -> str:
    shades, rails = [], []
    for (x, top, _), open_h, target, delay in zip(WINDOWS, OPENS, targets, delays):
        frames = keyframes(open_h, target, delay)
        shades.append(
            f'<rect x="{x}" y="{top}" width="68" height="{open_h - top}" rx="6">'
            + animate("height", frames, lambda h, top=top: h - top)
            + "</rect>"
        )
        rails.append(
            f'<rect x="{x + 1}" y="{open_h - 5}" width="66" height="10" rx="2.5">'
            + animate("y", frames, lambda h: h - 5)
            + "</rect>"
        )

    line = ""
    if hemline:
        # The group's hemline: the highest shade's, which every other shade
        # joins on the way down and leaves at its own top on the way up.
        leader = OPENS.index(min(OPENS))
        frames = keyframes(OPENS[leader], targets[leader], delays[leader])

        def y(h: float) -> float:
            return 12.8 + 0.9 * h + 0.6  # into the page's coordinates

        line = (
            f'\n  <line x1="3" y1="{y(OPENS[leader]):.2f}" x2="253" y2="{y(OPENS[leader]):.2f}" '
            'stroke="#FF6B3D" stroke-width="3.2" stroke-linecap="round" stroke-dasharray="6 6">'
            + animate("y1", frames, y)
            + animate("y2", frames, y)
            + "</line>"
        )

    frames_svg = "\n      ".join(
        f'<rect x="{x}" y="{top}" width="68" height="{height}" rx="6"/>'
        for x, top, height in WINDOWS
    )
    nl = "\n      "
    return f"""<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" width="256" height="256">
  <title>{title}</title>
  <!-- Generated by make_animations.py -->
  <defs>
    <linearGradient id="glass" gradientUnits="userSpaceOnUse" x1="0" y1="122" x2="0" y2="246">
      <stop offset="0" stop-color="#FFCF6E"/>
      <stop offset="1" stop-color="#A9CCDB"/>
    </linearGradient>
  </defs>

  <g transform="translate(12.8 12.8) scale(0.9)">
    <g fill="url(#glass)">
      {frames_svg}
    </g>
    <g fill="#2E7182">
      {nl.join(shades)}
    </g>
    <g fill="none" stroke="#3B4A5A" stroke-width="8" stroke-linejoin="round">
      {frames_svg}
    </g>
    <g fill="#1F4F5C">
      {nl.join(rails)}
    </g>
  </g>{line}
</svg>
"""


if __name__ == "__main__":
    here = Path(__file__).parent
    (here / "shades-cover-group.svg").write_text(
        svg(
            "Cover group: shades set to 50% end at different heights",
            GROUP_TARGETS,
            GROUP_DELAYS,
            hemline=False,
        )
    )
    (here / "shades-aligned.svg").write_text(
        svg(
            "Aligned Shade Group: shades set to 50% stay level",
            ALIGNED_TARGETS,
            ALIGNED_DELAYS,
            hemline=True,
        )
    )
